# Generated by Django 6.0.2 on 2026-02-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_accountholding_accountstanding_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholding',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='accountholding',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AlterField(
            model_name='accountstanding',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stockID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
