# Generated by Django 6.0.2 on 2026-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_accountholding_accountid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='startBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
