# Generated by Django 6.0.2 on 2026-02-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_startbalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
