# Generated by Django 6.0.2 on 2026-02-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
