# Generated by Django 6.0.2 on 2026-02-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useraccount_delete_appuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountholding',
            old_name='accountID',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='accountholding',
            old_name='stockID',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='accountstanding',
            old_name='accountID',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='stockID',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='accountID',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='stockID',
            new_name='stock',
        ),
    ]
