# Generated by Django 6.0.2 on 2026-02-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_accountid_accountholding_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='accountID',
            new_name='account',
        ),
    ]
