# Generated by Django 6.0.2 on 2026-02-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_accountid_useraccount_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholding',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='accountholding',
            name='currentlyHeld',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='accountholding',
            constraint=models.UniqueConstraint(fields=('account', 'stock'), name='uniq_account_stock_holding'),
        ),
    ]
